dryrun = false
scanner = "clair"
failon = "high"
image_project = "your-project-here"
binauth_project = "your-project-here"
valid_repos = [
    "gcr.io/path/to/my/project",
]

trusted_builder-identities = [
    "email@example.com",
    "idcloudbuild.gserviceaccount.com"
]

trusted_projects = [
    "trusted-builds"
]

[checks]
diy      = true
nobody   = true
provenance = true
snakeoil = true

[server]
port = 8000
require_auth = true
username = "username here"
password = "bcrypt hash of your password"

[ejson]
dir = "/key"
secrets = "/etc/voucher/secrets.production.ejson"

[clair]
address = "localhost:6060"

[[repositories]]
org-name = "Shopify"
org-url = "https://github.com/Shopify"

[[repositories]]
org-name = "Grafeas"
org-url = "https://github.com/grafeas"

